### ISSUE TITLE
component[s1(脚本s1)] register error script spi component failed to load

### ISSUE THREAD

**Issue by Iceberry-qdd** [bryan31/liteflow-ext-rule-demo#3]
您好，我在尝试的时候报错：
```txt
2024-04-29T14:36:51.027+08:00  INFO 27796 --- [  restartedMain] com.yomahub.liteflow.core.FlowExecutor   : flow info loaded from class config with el,class=com.yomahub.liteflow.parser.sql.SQLXmlELParser
2024-04-29T14:36:51.076+08:00  INFO 27796 --- [  restartedMain] c.y.l.parser.sql.read.AbstractSqlRead    : query sql: SELECT * FROM chain WHERE application_name='SimpleDemo'
2024-04-29T14:36:51.239+08:00  INFO 27796 --- [  restartedMain] c.y.l.parser.sql.read.AbstractSqlRead    : query sql: SELECT * FROM script WHERE application_name='SimpleDemo'
2024-04-29T14:36:51.481+08:00  INFO 27796 --- [  restartedMain] c.y.liteflow.core.ScriptCommonComponent  : load script for component[s1(脚本s1)]
2024-04-29T14:36:51.482+08:00 ERROR 27796 --- [  restartedMain] com.yomahub.liteflow.flow.FlowBus        : script spi component failed to load
2024-04-29T14:36:51.483+08:00 ERROR 27796 --- [  restartedMain] c.y.l.builder.LiteFlowNodeBuilder        : An exception occurred while building the node[s1],component[s1(脚本s1)] register error script spi component failed to load

com.yomahub.liteflow.exception.ComponentCannotRegisterException: component[s1(脚本s1)] register error script spi component failed to load
	at com.yomahub.liteflow.flow.FlowBus.addNode(FlowBus.java:240) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.flow.FlowBus.addScriptNode(FlowBus.java:170) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.builder.LiteFlowNodeBuilder.build(LiteFlowNodeBuilder.java:149) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.parser.helper.ParserHelper.buildNode(ParserHelper.java:94) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.parser.helper.ParserHelper.parseNodeDocument(ParserHelper.java:135) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.parser.base.BaseXmlFlowParser.parse(BaseXmlFlowParser.java:39) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.parser.base.BaseXmlFlowParser.parse(BaseXmlFlowParser.java:25) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.parser.el.ClassXmlFlowELParser.parseMain(ClassXmlFlowELParser.java:16) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.core.FlowExecutor.init(FlowExecutor.java:174) ~[liteflow-core-2.12.0.jar:2.12.0]
	at com.yomahub.liteflow.springboot.LiteflowExecutorInit.afterSingletonsInstantiated(LiteflowExecutorInit.java:21) ~[liteflow-spring-boot-starter-2.12.0.jar:2.12.0]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:984) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.10.jar:6.0.10]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.1.jar:3.1.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.1.jar:3.1.1]
	at com.iceberry.simpledemo.SimpleDemoApplication.main(SimpleDemoApplication.java:14) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.1.1.jar:3.1.1]

2024-04-29T14:36:51.489+08:00 ERROR 27796 --- [  restartedMain] com.yomahub.liteflow.core.FlowExecutor   : An exception occurred while building the node[s1],component[s1(脚本s1)] register error script spi component failed to load

```
![image](https://github.com/bryan31/liteflow-ext-rule-demo/assets/59782644/0b928fa7-701e-4dde-a1de-b4c77e52bcb0)

###### 环境
* Spring Boot v3.1.1
* liteflow v2.12.0
* 配置文件采用连接数据库方式
* 连接PostgreSQL数据库

**Comment by Iceberry-qdd** [comment]
解决了，没有安装`groovy`依赖，安装后报错消失。
